//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int customer_id { get; set; }
        public string cust_first_name { get; set; }
        public string cust_last_name { get; set; }
        public string cust_address { get; set; }
        public string phone_number { get; set; }
        public string nls_language { get; set; }
        public string nls_territory { get; set; }
        public decimal credit_limit { get; set; }
        public string cust_email { get; set; }
        public Nullable<int> account_mgr_id { get; set; }
        public System.Data.Entity.Spatial.DbGeography cust_geo_location { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string marital_status { get; set; }
        public string gender { get; set; }
        public string income_level { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
