//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProject.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Departments = new HashSet<Department>();
            this.Warehouses = new HashSet<Warehouse>();
        }

		[DisplayName("Ubicación")]
		public int location_id { get; set; }
		[DisplayName("Dirección")]
		public string street_address { get; set; }
		[DisplayName("Código postal")]
		public string postal_code { get; set; }
		[DisplayName("Ciudad")]
		public string city { get; set; }
		[DisplayName("Estado")]
		public string state_province { get; set; }
		[DisplayName("País")]
		public Nullable<int> country_id { get; set; }
		
		public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
