//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int order_id { get; set; }
        public Nullable<int> line_item_id { get; set; }
        public int product_id { get; set; }
        public decimal unit_price { get; set; }
        public decimal quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductInformation ProductInformation { get; set; }
    }
}
