//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProject.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class OrderItem
    {
		[DisplayName("Órden")]
		public int order_id { get; set; }
        public Nullable<int> line_item_id { get; set; }
		[DisplayName("Artículo")]
		public int product_id { get; set; }
		[DisplayName("Precio unitario")]
		public decimal unit_price { get; set; }
		[DisplayName("Cantidad")]
		public decimal quantity { get; set; }

		[DisplayName("Órden")]
		public virtual Order Order { get; set; }
		[DisplayName("Artículo")]
		public virtual ProductInformation ProductInformation { get; set; }
    }
}
