//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProject.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }

		[DisplayName("Órden de compra")]
		public int order_id { get; set; }
		[DisplayName("Fecha")]
		public System.DateTime order_date { get; set; }
		[DisplayName("Tipo")]
		public string order_mode { get; set; }
		[DisplayName("Cliente")]
		public Nullable<int> customer_id { get; set; }
		[DisplayName("Estátus")]
		public string order_status { get; set; }
		[DisplayName("Total")]
		public Nullable<decimal> order_total { get; set; }
		[DisplayName("Vendedor")]
		public Nullable<int> sales_rep_id { get; set; }
		[DisplayName("Promoción")]
		public Nullable<int> promotion_id { get; set; }

		[DisplayName("Cliente")]
		public virtual Customer Customer { get; set; }
		[DisplayName("Vendedor")]
		public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
