//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProject.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class ProductDescription
    {
		[DisplayName("Producto")]
		public int product_id { get; set; }
		[DisplayName("Idioma")]
		public string language_id { get; set; }
		[DisplayName("Nombre")]
		public string translated_name { get; set; }
		[DisplayName("Descripción")]
		public string translated_description { get; set; }
    }
}
