//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductInformation()
        {
            this.Inventories = new HashSet<Inventory>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public Nullable<int> category_id { get; set; }
        public string weight_class { get; set; }
        public Nullable<System.DateTime> warranty_period { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public string product_status { get; set; }
        public decimal list_price { get; set; }
        public decimal min_price { get; set; }
        public string catalog_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
